### ISSUE TITLE
3-program problem

### ISSUE THREAD

**Issue by 23BCA309** [vtcbca/internal-exam-23BCA309#4]
plz explain the program ? and also in where i need to do this program ?

**Comment by amitvtcbb** [comment]
YOU HAVE TO CREATE TEXT FILE USING WRITER OBJECT. ENTER LINE TILL USER CHOISE. aFTER THAT TAKE 2 VARIBALE START AND END WHICH MEANS FROM WHERE YOU HAVE TO PRINT LINE . FOR EXAMPLE START =4 AND END=6 MEANS YOU HAVE TO PRINT LINE 4 TO 6 FROM FILE.

**Comment by 23BCA309** [comment]
I undestand now i know what i need to do in this program ,thank you.
