### ISSUE TITLE
solve this error

### ISSUE THREAD

**Issue by 23BCA309** [vtcbca/internal-exam-23BCA309#6]
![Screenshot (13)](https://github.com/user-attachments/assets/fe0cc36b-6db2-4955-bebf-d0c783337f57)

explain the last error and give any solution,plz

**Comment by 23bca300** [comment]
> ![Screenshot (13)](https://private-user-images.githubusercontent.com/177290093/369257788-fe0cc36b-6db2-4955-bebf-d0c783337f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDc0NjIsIm5iZiI6MTcyNjgwNzE2MiwicGF0aCI6Ii8xNzcyOTAwOTMvMzY5MjU3Nzg4LWZlMGNjMzZiLTZkYjItNDk1NS1iZWJmLWQwYzc4MzMzN2Y1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNDM5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmYzYTUyYjljNTUxNjFjMDdiOGZmYmFhZjMzZjlhMDI2ZDFjZjliMDMyM2E0OTJlYTEyYjgxNzA2NmY4ZWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rQUyxK_RvLU3o3yENmdug-d3Qd1WUgMNJFPtO0b5D1g)
> 
> explain the last error and give any solution,plz

please run the with statement line again

**Comment by 23BCA309** [comment]
i do it,but it still showing the same error

**Comment by 23bca261** [comment]
please run all sell one more time.

**Comment by 23bca300** [comment]
please run all cell one more time beacuse your "I/O close file error means" you closed the file

**Comment by 23bca275** [comment]
run all the cell one more time..

**Comment by 23BCA305** [comment]
@23BCA309 

run all the cell one more time
in run option and click on
run all cells

**Comment by 23BCA309** [comment]
it's not working

**Comment by 23bca290** [comment]
create a new file and check it...

**Comment by 23BCA309** [comment]
it's still not working i also tried 
it in idle
